### ISSUE TITLE
Vipps not connected to woocommerce 

### ISSUE THREAD

**Issue by narinder11** [vippsas/vipps-woocommerce#101]
Plugin :- Checkout with Vipps for WooCommerce

Error "Vipps not yet correctly configured: please go to the Vipps settings to complete your setup: Access denied due to invalid subscription key. Make sure to provide a valid key for an active subscription."

I have to face above error when i configure payment vipps method

**Comment by iverok** [comment]
The error message is directly from Vipps itself: The subscription key you are using is not correct. You should go to the Vipps Portal (portal.vipps.no) and get correct keys from the developer section. Please ensure that you are using live keys if not in test mode and vice versa.

**Comment by amitsarkerr** [comment]
Hi,

I am experiencing the same issue. I have filled in the required fields from the Vipps Developer Portal, but I am still encountering the same error.

Any suggestions would be greatly appreciated.

**Comment by iverok** [comment]
If you are getting this error, in particular on the settings screen, then your subscription key isn't valid. You will need to re-check both it, the MSN and verify that you are using test-keys only in the test environment (and vice versa). 

There have been, _very_ rarely, some issues where som older MSN could not get valid subscription keys set up. If this is the case, it has to be handled by Vipps themselves, but first please check _very thoroughly_ that the MSN, test/live setup, sub key and client id/secret are correct.

**Comment by amitsarkerr** [comment]
Hi Iverok,

Thank you for your reply.

I contacted Vipps support, and they confirmed that there is no issue with the MSN or API.

I have checked the API key setup multiple times, and everything appears to be correct. The test keys are working perfectly.

**Comment by iverok** [comment]
As mentioned on wp.org, please triplecheck that you are not using test keys in the live environment first,  then contact us directly so we can do some tests with your setup.  There has been some issues with some MSNs and keys, but extremely rarely and it's apparently not trivial for Vipps to detect.

**Comment by amitsarkerr** [comment]
I have already checked the MSN and API keys multiple times. Both production and test MSN, API keys are different.

How can I contact support directly?

**Comment by iverok** [comment]
For the record, just send an email to support@wp-hosting.no, but I see we are already in contact.
