### ISSUE TITLE
Updating shipping details upon Vipps checkout doesn't change shipping details

### ISSUE THREAD

**Issue by magnusfinset** [vippsas/vipps-woocommerce#11]
Hi there. I recently discovered a issue where changing shipping details in the Vipps App doesn't affect the order information transferred to Woocommerce. 

If the customer has an old adress in Vipps and changes this during the checkout the new adress is not sent to the Woo-order. The old adress is still present and this has lead to reshipping of plural items. 

Is there anyone else having this issue?

Website: https://particles.no

Best regards,
Magnus Finset

**Comment by magnusfinset** [comment]
> Hi @magnusfinset
> 
> @iverok from WP-Hosting knows the most about this.
> 
> Could you please describe the process to reproduce, step by step?
> 
> Btw: The most commonly used support "channel" is the support forum here (but we try to help everywhere): https://wordpress.org/support/plugin/woo-vipps
> 
> Christian, Vipps

Hi Christian! Thanks for such as fast reply. Wasn't sure where to post this issue but I will save the link for later. 

1. Add product to basket
2. Choose Pay with Vipps
3. Enter mobile number
4. Be sent to Vipps app
5. Enter the "Shipping details" section
6. Choose "home adress"/"Change home adress"
7. Enter new adress, press OK
8. Press "Finish" in top right corner
9. Check order details (Note: Adress appears to be changed)
9. Press "Pay"/"Complete payment"

10. Check order confirmation and payment in Woo
11. Old adress is present in order confirmation

**Comment by magnusfinset** [comment]
Tried to solve the issue by changing the shipping choices in Woocommerce settings. We have used "Force shipping to delivery adress" and I thought this might be the source to the issue. Unfortunately the problem is still current. 

Note:
1. Change adress in Vipps during checkout
2. Adress doesn't actually update in the current order, but the adress is changed and saved in the Vipps app for later purchases.

**Comment by iverok** [comment]
This is for express checkout, right?

**Comment by magnusfinset** [comment]
> This is for express checkout, right?

Yes, this is regarding the express checkout.

**Comment by magnusfinset** [comment]
We have not experienced this issue earlier so I suspect that the lates update might have caused it.

**Comment by iverok** [comment]
I think it probably has to do with a change having to do with logged-in customers using express checkout. I'll replicate and fix ASAP.

**Comment by iverok** [comment]
This was a bug in the app; as far as I can tell it has been fixed for a while now so I'll close this.
