### ISSUE TITLE
My account - not authenticated - Vipps logo stretched 

### ISSUE THREAD

**Issue by henningbra** [vippsas/vipps-woocommerce#118]
Disclaimer: uncertain if this is related to plugin or template

Logo is stretched and hard to read, see url and image:
[https://www.spraylakk.no/min-konto/](https://www.spraylakk.no/min-konto/)

<img width="901" alt="image" src="https://github.com/vippsas/vipps-woocommerce/assets/5746249/7c9bbcb1-5304-4082-9bce-7588a68e0e35">

**Comment by iverok** [comment]
You have code in your theme  that insists that images in this context should be width 100%. You can add this:

```
img.inline.vipps-logo.negative {
    max-width: 4rem;
}
```

--- as custom CSS. I'm adding something similar to the plugin for next version.
