### ISSUE TITLE
Untranslatable string

### ISSUE THREAD

**Issue by knutsp** [vippsas/vipps-woocommerce#122]
Untranslatable string: 'Select link type' in
https://github.com/vippsas/vipps-woocommerce/blob/bc2451589f9626542a63ef4f6882ad93a0a5c694/VippsQRCodeController.class.php#L327

**Comment by knutsp** [comment]
Also for 'Download as SVG' and 'Download as SVG' and 'Download as PNG' button labels further down in the same file.

**Comment by iverok** [comment]
Right you are; 2.0.11 fixes these.
