### ISSUE TITLE
[BUG] Uncaught Error stops execution completely

### ISSUE THREAD

**Issue by DuncanConroy** [vippsas/vipps-woocommerce#132]
Using latest version from 18. Jun 2024. Whenever one visits a page of the shop, WP shows an error and doesn't render the page.
The stack trace shows this:
```php
PHP Fatal error:  Uncaught Error: Call to undefined function wc_get_logger() in /var/www/html/wp-content/plugins/woo-vipps/Vipps.class.php:1261\nStack trace:\n#0 /var/www/html/wp-content/plugins/woo-vipps/Vipps.class.php(137): Vipps->log('Feil: Kunne ikk...', 'error')\n#1 /var/www/html/wp-content/plugins/woo-vipps/Vipps.class.php(2142): Vipps->gateway()\n#2 /var/www/html/wp-content/plugins/woo-vipps/Vipps.class.php(2229): Vipps->get_payment_method_name()\n#3 /var/www/html/wp-includes/class-wp-hook.php(324): Vipps->plugins_loaded('')\n#4 /var/www/html/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters(NULL, Array)\n#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)\n#6 /var/www/html/wp-settings.php(555): do_action('plugins_loaded')\n#7 /var/www/html/wp-config.php(134): require_once('/var/www/html/w...')\n#8 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')\n#9 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')\n#10 /var/www/html/index.php(17): require('/var/www/html/w...')\n#11 {main}\n  thrown in /var/www/html/wp-content/plugins/woo-vipps/Vipps.class.php on line 1261, referer: https://crazydogs.no/
```

The index page is cached by cloudflare, which explains why we don't see an error there. All other pages produce this same stack trace.

We are on Autoupdate for both vipps and woocommerce. I believe this happened after a woocommerce update that needed a database upgrade, which was still pending. Just a guess.

I have rolled back the DB and could fix the issue for us.

**Comment by iverok** [comment]
Not sure how this happens, because the error was triggered in "plugins_loaded" when Woo hasn't been loaded yet. But Woo is a dependency of the plugin, so it should really be impossible.

Nevertheless, version 2.1.5 will fix this by logging to the system log instead of trying to get the woo logging facility if this happens.
