### ISSUE TITLE
Error message when cancelling order

### ISSUE THREAD

**Issue by knutsp** [vippsas/vipps-woocommerce#136]
The message "Could not refund payment through %1$s - ensure the refund is handled manually!" appears when (bulk) cancelling an order, even when payment is not captured. Cancelling an order with not captured amount should go silent, as no action is needed.

**Comment by iverok** [comment]
That should not happen - this error message is only generated from the "maybe_refund_payment" method, which is only called when orders are cancelled in this case:

`      // Now first check to see if we have captured anything, and if we have, refund it. IOK 2018-05-07
        $captured = intval($order->get_meta('_vipps_captured'));
        $vippsstatus = $order->get_meta('_vipps_status');
        if ($captured || $vippsstatus == 'SALE') {
            return $this->maybe_refund_payment($orderid);
        }
`

Could you check the "full order status at Vipps" for the order where you see this error?

**Comment by knutsp** [comment]
It was bulk, and it seems one was catured in test mode.

**Comment by iverok** [comment]
Phew! Thank you for reporting and checking it out.
