### ISSUE TITLE
Payment method not changed in Woo after first trying Vipps, then changing to another payment method

### ISSUE THREAD

**Issue by orjansteffensen** [vippsas/vipps-woocommerce#14]
So, first off, I’m not sure if this is an issue for Vipps, Klarna or Woocommerce in general.

We have Klarna and Vipps as payment options. On some orders the customer starts payment via Vipps. The payment then fails, probably due to insufficient funds, the customer goes back and chooses to pay via Klarna. The order then goes through as it should.

The problem is that Vipps is still the registered payment method on the order data. So when we try to complete the order it prompts Vipps to capture the payment (which obviously fails) and we have to go in manually on the Woo order, change payment method to Klarna, before also logging into Klarna to activate the order there before being able to complete the order.

In the screenshot you can see the statuses of a customer who has done this. She started out with Vipps, but changed to Klarna after a failed payment via Vipps. The status bar does not catch this however.

![2019-05-02 12_03_54-Rediger ordre ‹ Organized no — WordPress](https://user-images.githubusercontent.com/24268072/57071860-05f41d00-6cdc-11e9-989e-800ac1c23125.png)

**Comment by iverok** [comment]
That's really weird. It works like that when the orders' payment_method() returns 'vipps' and only then - and this ought to be overwritten by the other method when chosen. I will try to replicate it and see if there is a bug in the Vipps plugin or if I can at least fix whatever else may be causing it.

**Comment by iverok** [comment]
I tried to replicate with COD, but choosing that sets the payment-method correctly when changing payment methods - ie, after restarting the order using "COD", the payment_method() of the order is no longer 'vipps' and the Vipps logic is removed. Will investigate further.

**Comment by orjansteffensen** [comment]
Forgot to mention that we have a somewhat special setup, in case this has something to do with it.

We use landing pages with integrated checkout on the pages. In addition we use Klarna as standard payment gateway, and have some custom code that integrates the Vipps plugin into the Klarna gateway. 

![2019-05-03 09_35_33-Lærerplanlegger for 2019_20 – A4-format _ Organized no](https://user-images.githubusercontent.com/24268072/57124674-ea921c00-6d86-11e9-84b2-a0b63248658c.png)

See live example at bottom of this page: https://www.organized.no/laererplanlegger/

**Comment by iverok** [comment]
Just to be sure: Are you using the "Klarna Checkout" plugin, ie the 'kco' payment method?

**Comment by orjansteffensen** [comment]
Yes.

**Comment by iverok** [comment]
Which version of Woocommerce are you using?  There is a file "includes/class-wc-form-handler.php" there that has a method pay_action() that should do set_payment_method()  and order_save() before calling process_payment() on the new payment method. 

In previous versions I see that this only called "update_post_meta" for the payment method settings, which *may* be a bug in that version.  It may also be the case that the Klarna plugin has its own logic here, as it does replace the normal Checkout logic.

There are some filters and hooks you could use to check this further:

 $result = apply_filters( 'woocommerce_payment_successful_result', $result, $order_id );

and

  do_action( 'woocommerce_after_pay_action', $order );

- when these fire,  the payment_method_id should still be in the variable  $_POST['payment_method']   (and in the session WC()->session->get( 'chosen_payment_method' ), but the POST variable is what is posted here).

You should be able to call set_payment_method in these filters if the orders' payment_method is not the same as what is POST'ed.

**Comment by orjansteffensen** [comment]
Woocommerce is updated, so using 3.6.2 now. 

As for the filters and hooks, I'm a too amateur to try those out and work mainly front end. But I should perhaps ask the Klarna github if this is due to their plugin?

**Comment by iverok** [comment]
It could be that it does not set the payment_method when payment is changed on an order, but if so it is probably because it assumes it is the only available payment method when installed, which is part of the featureset of Klarna Checkout. So they might not recognize this as a bug at all.  

As changing payment method does work with COD, I'm not comfortable hooking into 'after pay action' in this plugin just to do sanity checking, but it could make sense as a separate plugin with code as described above.

As a side note, when the Vipps payment fails, the order will actually normally be cancelled (still - there has been requests to change this behaviour) to ensure metadata is consistent with the Vipps transaction, so there is typically just a small time window for restarting the transaction with another payment method.

**Comment by cloveras** [comment]
Hi, @orjansteffensen 

Just checking if we (read: @iverok) can offer more help, or if we should close this issue? 

Christian, Vipps

**Comment by orjansteffensen** [comment]
Sorry about not responding earlier. Appreciate the help and suggestions. I'll also contact the Klarna devs in case this is something they can fix in future versions.
