### ISSUE TITLE
404's in links from README.md 

### ISSUE THREAD

**Issue by unhammer** [vippsas/vipps-woocommerce#15]
The readme links twice to https://www.vipps.no/bedrift/vipps-pa-nett/woocommerce/
which seems to be the first step to getting started. How do I get started? :-)

**Comment by unhammer** [comment]
Found https://www.vipps.no/produkter-og-tjenester/bedrift/ta-betalt-paa-nett/ta-betalt-paa-nett/woocommerce/ which seems like it might be what I need – maybe the readme should point to that? Or https://vippsbedrift.no/signup/vippspanett/ ?

**Comment by iverok** [comment]
Thank you for the report - I'll fix it for next release.

**Comment by flinkgutt** [comment]
This has been fixed in PR https://github.com/vippsas/vipps-woocommerce/pull/16 which iverok merged in two hours ago.

Thank you very much for your issue report =)
