### ISSUE TITLE
Vipps Checkout page missing after upgrade to version 3.0.5

### ISSUE THREAD

**Issue by henningbra** [vippsas/vipps-woocommerce#158]
Following always been activated:

![Image](https://github.com/user-attachments/assets/f9a5dd43-80fe-4c26-9f7a-c7f1603de113)

But the Vipps checkout page is missing, including the option paying with credit card

**Comment by iverok** [comment]
Seems the fix in 3.0.5 fixes a bit too much. Looking into it.

**Comment by iverok** [comment]
Sorry about that, we messed up testing impressively for 3.0.5. 

 3.0.6 will be out shortly which should solve the issue. NB: The link to the checkout page in the _mini cart_ is cached and will not change until the cart itself changes. The link on the cart page will change.

In cases of further issues like this, a temporary fix may be to just find the "Vipps Checkout" page in your pages-list and point customers directly to that while we fix it - it will work even if it is not the "official" Woo Checkout page.

**Comment by henningbra** [comment]
Works with latest version 3.0.6

Your prompt response and actions are highly appreciated!
