### ISSUE TITLE
Is this plugin compatible with vipps-recurring-api

### ISSUE THREAD

**Issue by Preen** [vippsas/vipps-woocommerce#21]
Investigating if it's possible to this plugin with recurring payments.
https://github.com/vippsas/vipps-recurring-api

**Comment by iverok** [comment]
Unfortunately not; the Recurring API is very different from the Ecommerce-api and not just an extension.  The recurring API would need its own complete implementation.

**Comment by Preen** [comment]
Ohh I see, thanks for the fast answer, do you by any chance know any that have done this? Or if there is an example?

**Comment by cloveras** [comment]
Hi @Preen 

You can have a look at https://dipr.no. Not WordPress, but a nice example. 

Christian, Vipps

**Comment by Preen** [comment]
Thanks @cloveras

**Comment by iverok** [comment]
A separate plugin will provide this feature shortly (?), so I'm closing this.

**Comment by Preen** [comment]
Awesome @iverok!!!

**Comment by Preen** [comment]
@iverok do you have any timeframe of when this feature will be released? And will there be a beta stage? :)

**Comment by iverok** [comment]
I don't know - I'm not involved with the separate plugin  at all; but it is supposed to be pretty ready.

**Comment by Preen** [comment]
@iverok if they need beta testers. We are more than willing to do be part of that :)
