### ISSUE TITLE
Express checkout is not defaulting to logged in user phone number

### ISSUE THREAD

**Issue by s0ndre** [vippsas/vipps-woocommerce#22]
It would be great if an already logged in Vipps user did not have to enter phone number again when doing express checkout.

**Comment by iverok** [comment]
Current "process_payment()" method fetches phone from checkout page only; it should default to what current_user has in billing_phone or whatever is stored in the session.

**Comment by iverok** [comment]
Fixed in 'master' branch and will be released in next version.

**Comment by iverok** [comment]
Fixed.
