### ISSUE TITLE
Vipps Hurtigkasse on single products

### ISSUE THREAD

**Issue by thoaud** [vippsas/vipps-woocommerce#4]
Parts of the greatness about Vipps is the ease of use, with the possibility of checking out one single product easily. The landing page for [Vipps for Woocommerce](https://www.vipps.no/bedrift/vipps-pa-nett/woocommerce) states that the "hurtigkasse" can be added to single products, cart or the checkout. But, it seems the single product option is missing at this point? Am I correct or have I just missed it?

**Comment by iverok** [comment]
Not yet implemented, but planned for next release, together with "Buy now" link for banner ads and so forth.

**Comment by iverok** [comment]
This will be in 1.1.0 which is in testing. 1.0.6 will come before that and will contain bugfixes and more actions and hooks.

There will also be shortcodes and a facility for creating links that can be added to banners and so forth, and filters for all this.

**Comment by iverok** [comment]
This is now pushed to the master branch on github. Release planned for monday.

**Comment by iverok** [comment]
Now live.
