### ISSUE TITLE
Possible Typing error

### ISSUE THREAD

**Issue by shattique** [vippsas/vipps-woocommerce#45]
In version 1.4.4, there is a possible typing error for a break from a loop, in Vipps.class.php. It's inside the shipping callback handler method, line number 1164. It's written $break;

**Comment by iverok** [comment]
Thank you for spotting, embarrasing typo fixed and pushed to wp.org as current version, new version on github is 1.4.4.1. This bug was introduced 14. february and has been present on released version since version 1.4.0.  

"$break", good grief.
