### ISSUE TITLE
Undefined variable issues

### ISSUE THREAD

**Issue by shattique** [vippsas/vipps-woocommerce#46]
In version 1.4.5, there are two undefined variable errors in the WC_Gateway_Vipps.class.php file. Both are in refund_superfluous_capture function.
1. LIne 978, variable = $orderid
2. Line 988, variable = $reason

**Comment by iverok** [comment]
That's weird, those bits haven't been changed for a long time. Looking into it before release, thank you.

**Comment by iverok** [comment]
The bugs have been there since they were first commited; reason is that the error-logging and ordernote code here has been copied from the regular refund branch, where orderid and reason were available.  Fixed,  uploading to github and wp.org shortly.
