### ISSUE TITLE
Improvement: Use actions for placements and filters for markup adjustments of Vipps Hurtigkasse

### ISSUE THREAD

**Issue by thoaud** [vippsas/vipps-woocommerce#5]
When developing a more advanced WooCommerce store than the average "buy a theme and set it up" a developer would need actions to place within the custom template. Same goes for filters to change the markup of the elements placed.

I would like actions and filters on the following:
- Vipps hurtigkasse on product pages
- Vipps hurtigkasse on single products in the product loop
- Vipps Hurtigkasse on cart/checkout

I am developing a WooCommerce store with 35-40MNOK annual revenue, and these features among others is critical for us to even be able to use this plugin and Vipps.

**Comment by iverok** [comment]
Next release is planned to add hooks, filters and shortcodes.  Please list any you feel are needed. In addition to the express checkout bits,  the shipping methods callback certainly needs a filter.

**Comment by iverok** [comment]
Some more filters and hooks have been added.  Hurtigkasse on single products is up next.

**Comment by iverok** [comment]
"master" branch now updated with filters, actions and shortcodes, and single product express checkout feature. Release planned for monday.

**Comment by iverok** [comment]
Now live.
