### ISSUE TITLE
Improvement: Start tagging releases on github and make it ready for composer

### ISSUE THREAD

**Issue by thoaud** [vippsas/vipps-woocommerce#6]
Since most modern and professional developers use composer (or other dependency managers) to pull in plugins, a combination of getting the repository composer ready (composer.json) and starting to tag releases on github would be a good idea. 

This would ease the work when developing larger stores in a professional environment.

**Comment by iverok** [comment]
Tagging releases is a good idea so I'll start pushing tags to github from next version.

As for composer, the plugin is intented to be installed and updated from the standard wp.org plugin repository. As such, it should be available thru https://wpackagist.org/ . 

Of course, adding a composer.json file can't hurt if you prefer to have it part of the repos.

**Comment by thoaud** [comment]
Sure, and most will probably use wpackagist too. I however prefer to grab releases from github if possible. That also makes it easier to contribute with testing without disrupting the regular dependency management.
