### ISSUE TITLE
Add a filter for Checkout args in vipps-checkout.js

### ISSUE THREAD

**Issue by Marcuzz** [vippsas/vipps-woocommerce#78]
Hey,

We have a use-case where we need to conditionally set [addressFields](https://github.com/vippsas/vipps-checkout-api/blob/main/vipps-checkout-api.md#modularity-of-vipps-checkout-fields) to false, and it would be useful if you could add a filter for the args passed to VippsCheckout in the frontend, here: https://github.com/vippsas/vipps-woocommerce/blob/master/js/vipps-checkout.js#L67-L72

**Comment by iverok** [comment]
Like so:

` let args = {
                     checkoutFrontendUrl: VippsSessionState['checkoutFrontendUrl'].replace(/\/$/, ''),
                     token:  VippsSessionState['token'],
                     iFrameContainerId: "vippscheckoutframe",
                     language: VippsConfig['vippslanguage']
         };
         if (typeof wp !== 'undefined' && typeof wp.hooks !== 'undefined') {
             args = wp.hooks.applyFilters('vippsVippsCheckoutArgs', args);
         }`

? I can add that, but I don't see how this will affect the addressFields. The customer information is actually passed from server to Vipps in the inititate_checkout call, would it help to add a filter in the backend code, like

` $customerinfo = apply_filters('woo_vipps_customerinfo', $customerinfo, $order);`

The Vipps Checkout frontend code runs in an iframe hosted at Vipps, so we can't inject code there.

**Comment by Marcuzz** [comment]
You're right.

If I'm reading the API docs correctly I should already be able to achieve this by using the `woo_vipps_initiate_payment_data` hook?

**Comment by iverok** [comment]
Yes, that will work. I'm adding the customerinfo-specific filter now anyway, but if you need a quick  solution, go with that.
