### ISSUE TITLE
Order confirmation bug when purchasing via inapp browsers

### ISSUE THREAD

**Issue by orjansteffensen** [vippsas/vipps-woocommerce#8]
When purchasing via Instagram inapp-browser and paying with Vipps the customer is not receiving order confirmation. Instead a basic page where "Unknown order" is displayed. Alternative page that loads sometimes is "Order cancelled". Payments are correctly processed though, and the order is correctly registered in Woocommerce. Tested on both iOS and Android. This seems to be a problem with Facebook inapp as well.

![img_8641](https://user-images.githubusercontent.com/24268072/48616346-a0151280-e993-11e8-968e-b757112455e3.PNG)

**Comment by iverok** [comment]
The order will be correctly handled by the callback; but this means that the woocommerce session isn't preserved in the in-app browser. There is normally no order-information passed from Vipps to the return page, so the session has to be active for this page to work. 

I'll look for a workaround.

**Comment by orjansteffensen** [comment]
I see. Confirmation page is opened in standard browser, instead of going back to in-app so the solution would be to open the confirmation page in in-app as well if possible?

**Comment by iverok** [comment]
Ah, that would cause it, yes.  I think the app probably should use the in-app browser on return, but I don't know if that's possible, and the Woo plugin can't help with this.

I'll try to raise the issue. If it can't be done, I'll try to see if the session can be ported somehow.
