### ISSUE TITLE
Scheduled actions - Vipps recurring

### ISSUE THREAD

**Issue by esbnews** [vippsas/vipps-woocommerce#88]
Hi

My system generates an error connected to Vipps fast trekk and Woocommerce Subscriptions when a recurring action runs: 

"scheduled action 188853 (subscription payment) failed to finish processing due to the following error: Uncaught ArgumentCountError: 3 arguments are required, 2 given in /customers/3/d/8/xxxxx.no/httpd.www/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/templates/emails/customer-processing-renewal-order.php:19"

I wonder how to work this out, and am not sure if it's a Vipps problem or Woocommerce Subscriptions problem. I got the full errorlog if anyone can look at this.

Best regards, Esben Holm Eskelund

**Comment by iverok** [comment]
This plugin doesn't support WooCommerce subscriptions; I think you want the Vipps Recurring Payments plugin which is here:

https://github.com/vippsas/vipps-recurring-woocommerce

and here:

https://wordpress.org/plugins/vipps-recurring-payments-gateway-for-woocommerce/

That gateway and this uses completely different APIs so I'm sorry that we can't help you with this.

**Comment by esbnews** [comment]
I see, thanx for directions!
