### ISSUE TITLE
Navigating back after using the vipps-buy-now button

### ISSUE THREAD

**Issue by kimhf** [vippsas/vipps-woocommerce#99]
The usage of `window.location.replace(result["url"]);` makes it impossible to navigate back to the product after having initiated the purchase. 

This seems to both apply if the user immediately tries to navigate back after having clicked the button, or if the customer aborts the process in the app. It should be simple for the customer to find the product again, especially as it might not be in the cart. Most users will expect navigating back to take them to the product page.

Changing `window.location.replace(result["url"]);` with `window.location.assign(result["url"]);` could be a possible solution.

**Comment by cloveras** [comment]
Hello! There is a support forum at https://wordpress.org/support/plugin/woo-vipps/, but now that we're here I think you'll get help directly from the developer here too.

**Comment by iverok** [comment]
Here is fine for detailed code suggestions (or patches!) @kimhf Have you tried your suggested replacement here?  I haven't really looked at backbutton usage in this flow and it hasn't come up as a support issue yet, but any improvement is of course welcome.

**Comment by kimhf** [comment]
@cloveras I do have another issue that I can bring up in the support form instead as I don't have any specific code suggestions for that one.

@iverok I have not tested it other then identifying a possible solution/improvement. I can test it out and will get back with the result.

**Comment by iverok** [comment]
I've replaced .replace with .assign and it does enable the back button (although one also has to fix the disabled buttons and spinners when that happens.)  Pushed to 'master',  There *may* be a release soon but it may be delayed to end of july due to holidays.

**Comment by iverok** [comment]
1.14.8 should fix this.
